### ISSUE TITLE
System573 audio offset plugins don't seem to work starting in MAME 0.261

### ISSUE THREAD

**Issue by sillybear** [987123879113/mame_cheats#1]
I tried to change just the global default value inside settings.json (like between "28ms" to "80ms") and using DDR EXTREME, and they have no effect.

**Comment by 987123879113** [comment]
Could you try the upstreamed version of the plugin here? The one in my repository here is the original code and the one in the mamedev/mame-goodies repo is the updated version (mostly just structural and usage changes, functionally should be the same) so I'd recommend using that one instead if it works.

https://github.com/mamedev/mame-goodies/tree/master/plugins/ksys573_da_offset

**Comment by sillybear** [comment]
I can confirm, the link you gave me finally worked on MAME 0.261, both windows and android version. Thanks!

**Comment by 987123879113** [comment]
Thanks for the update. I'll modify this repo to point to the mame-goodies version instead then.
